resources:
  repositories:
    - repository: templates
      type: github
      endpoint: github
      name: ccdc-opensource/conan-azure-devops
      ref: refs/heads/development

extends:
  template: third-party-library-all-platforms-from-conan-center.yml@templates
  parameters:
    package: winflexbison
    package_version: 2.5.24
    source_repository: public-conan-center
    destination_repository: ccdc-3rdparty-conan
    platforms:
      - win2019_vs2019
    build_types:
      - Release
